'use strict';

/**
 * Datos compartidos de la entrega (Consigna 7) y de las respuestas teóricas.
 *
 * Lo consumen tanto tp-final-generator/generate-tp-final.js como
 * docx-generator/generate-docx.js. Como cada generador corre en su propio
 * contenedor pero monta el proyecto en /work, ambos lo importan vía
 * require('/work/shared/qa-data.js'). Es un módulo de datos puro (sin
 * dependencias externas), por lo que no necesita node_modules.
 */

// ── Equipo (portada) ──────────────────────────────────────────────────────────
const AUTHORS = [
  'Esquivel, Claudio Daniel',
  "Fernandes D'Oliveira, Alejandro",
  'Giuggio, Mario Sebastián',
  'Nehmi, Karim Eduardo Fayad',
  'Pan, Eric Damián',
  'Terzano, Carlos Guillermo',
];

// ── Enunciados (para citar la consigna antes de cada respuesta) ────────────────
const ENUNCIADOS = {
  q1: 'Pensando en que los casos de prueba representan la funcionalidad viva de la aplicación, ¿cómo organizaría la casuística si se tienen que realizar tanto pruebas funcionales como de look&feel? Justifique.',
  q2: '¿Cómo organizaría las pruebas tempranas del frontend si no está listo el backend? Justifique.',
  q3: 'En cuanto a las pruebas de backend, ¿cómo organizaría la cobertura de cada servicio, a fin de poder ejecutarlas en cada despliegue con cambios? ¿Qué prácticas de testing incluiría?',
  q4: '¿Qué potenciales problemas podrían encontrarse al poner en producción las funcionalidades existentes, donde se espera mucho tráfico en pocas horas? (por ejemplo, fichaje de ingreso/egreso por turnos).',
  q5: '¿Cómo intentaría descubrir los problemas del punto 4 antes de que sean problemas reales en producción? Indique actividades y su frecuencia, justificando.',
  q6: '¿Cómo organizaría su equipo de testing para poder realizar todas las pruebas durante cada sprint?',
  q7: 'Suponiendo el desarrollo incremental Sprint N a N+3, entregar: a) Plan de pruebas general; b) Diseño de casos de prueba de frontend del Sprint N, N+1 y N+2 (Actividad 2), resultado de ejecución y reporte de bugs; c) Diseño de casos de prueba de la API del Clima (Actividad 3) e inclusión de la colección de Postman; d) Reporte de las pruebas ejecutadas y reporte de bugs encontrados.',
  q8: 'Al poner el sitio en producción, el negocio planifica 3 sprints adicionales para incorporar Recruitment. Analizar cómo implementarlo, recursos necesarios y planificación de pruebas (sin armar un plan nuevo).',
};

// ── Casos de prueba Frontend detallados (Actividad 2) ─────────────────────────
// Cada caso: { id, tipo, estado, titulo, pre, datos, pasos[], esperado, obtenido }
const FRONTEND_SPRINTS = [
  {
    sprint: 'Sprint N',
    desc: 'Backend de Employee List y Add Employee · Pantallas de Employee List, Add Employee y My Info – Qualifications.',
    modules: [
      {
        name: 'PIM – Employee List', range: 'CP-001 a CP-005',
        cases: [
          { id: 'CP-001', tipo: 'SMOKE + REGRESIÓN', estado: 'PASÓ',
            titulo: 'La tabla de empleados carga correctamente',
            pre: 'Usuario Admin logueado.', datos: 'N/A',
            pasos: ['Iniciar sesión como Admin', 'Ir a PIM > Employee List', 'Esperar la carga de la grilla'],
            esperado: 'Se muestra la grilla (.oxd-table) con al menos una fila y la pantalla contiene el texto "Employee".',
            obtenido: 'PASÓ: la grilla carga con filas y el encabezado correcto.' },
          { id: 'CP-002', tipo: 'REGRESIÓN', estado: 'FALLÓ',
            titulo: 'Búsqueda por nombre filtra resultados',
            pre: 'En PIM > Employee List.', datos: 'Employee Name = "Admin"',
            pasos: ['Escribir "Admin" en el campo Employee Name', 'Seleccionar la primera sugerencia del autocomplete', 'Click en Search'],
            esperado: 'La grilla muestra filas que coinciden con el nombre, o el mensaje "No Records Found", sin error.',
            obtenido: 'FALLÓ: timeout intermitente esperando la sugerencia/resultado por latencia del demo público compartido. No es defecto de producto (deuda de automatización: aumentar timeout / estabilizar selector).' },
          { id: 'CP-003', tipo: 'REGRESIÓN', estado: 'SALTADO',
            titulo: 'Búsqueda por Employee ID muestra un empleado específico',
            pre: 'Existen empleados en la grilla.', datos: 'Primer Employee ID visible en la tabla',
            pasos: ['Tomar el primer Employee ID de la grilla', 'Ingresarlo en el campo Id', 'Click en Search'],
            esperado: 'La grilla muestra exactamente 1 fila cuyo Id coincide con el buscado.',
            obtenido: 'SALTADO: dependía del flujo de filtrado de CP-002.' },
          { id: 'CP-004', tipo: 'FUNCIONAL', estado: 'PASÓ',
            titulo: 'El botón Reset limpia el formulario de búsqueda',
            pre: 'En PIM > Employee List.', datos: 'Id = "99999"',
            pasos: ['Ingresar 99999 en el campo Id', 'Verificar que el valor quedó cargado', 'Click en Reset'],
            esperado: 'El campo Id queda vacío luego del Reset.',
            obtenido: 'PASÓ (ver BUG-01: otros filtros como Employment Status no se limpian del todo).' },
          { id: 'CP-005', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'La tabla muestra las columnas esperadas',
            pre: 'En PIM > Employee List.', datos: 'N/A',
            pasos: ['Leer los encabezados de la grilla'],
            esperado: 'Los encabezados incluyen columnas de Id, First/Name y Last name.',
            obtenido: 'PASÓ.' },
        ],
      },
      {
        name: 'PIM – Add Employee', range: 'CP-006 a CP-010',
        cases: [
          { id: 'CP-006', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'El formulario de alta carga correctamente',
            pre: 'Admin logueado.', datos: 'N/A',
            pasos: ['Ir a PIM > Add Employee'],
            esperado: 'Se ve el título "Add Employee", los campos firstName y lastName y los botones Save y Cancel.',
            obtenido: 'PASÓ.' },
          { id: 'CP-007', tipo: 'REGRESIÓN', estado: 'PASÓ',
            titulo: 'Crear empleado con datos mínimos obligatorios',
            pre: 'En PIM > Add Employee.', datos: 'First Name y Last Name únicos generados',
            pasos: ['Completar First Name y Last Name', 'Click en Save', '(limpieza) buscar y eliminar el empleado creado'],
            esperado: 'El sistema crea el empleado y redirige a Personal Details del nuevo legajo.',
            obtenido: 'PASÓ.' },
          { id: 'CP-008', tipo: 'REGRESIÓN', estado: 'PASÓ',
            titulo: 'Guardar sin datos muestra errores de validación',
            pre: 'En PIM > Add Employee.', datos: 'Formulario vacío',
            pasos: ['Click en Save sin completar campos'],
            esperado: 'Aparecen uno o más mensajes de validación ("Required") en los campos obligatorios.',
            obtenido: 'PASÓ.' },
          { id: 'CP-009', tipo: 'FUNCIONAL', estado: 'PASÓ',
            titulo: 'El campo Employee ID se pre-popula automáticamente',
            pre: 'En PIM > Add Employee.', datos: 'N/A',
            pasos: ['Abrir Add Employee', 'Leer el campo Employee Id'],
            esperado: 'El campo Employee Id trae un valor por defecto (no vacío).',
            obtenido: 'PASÓ.' },
          { id: 'CP-010', tipo: 'FUNCIONAL', estado: 'PASÓ',
            titulo: 'El botón Cancel regresa al listado sin crear empleado',
            pre: 'En PIM > Add Employee.', datos: 'First Name/Last Name temporales',
            pasos: ['Completar nombre y apellido', 'Click en Cancel'],
            esperado: 'Vuelve a Employee List y no se crea ningún empleado.',
            obtenido: 'PASÓ.' },
        ],
      },
      {
        name: 'My Info – Qualifications', range: 'CP-011 a CP-015',
        cases: [
          { id: 'CP-011', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'La pestaña Qualifications carga y muestra sus secciones',
            pre: 'Admin logueado; perfil de un empleado abierto.', datos: 'N/A',
            pasos: ['Abrir el perfil de un empleado (PIM)', 'Ir a la pestaña Qualifications'],
            esperado: 'Se ven las secciones Work Experience y Education.',
            obtenido: 'PASÓ.' },
          { id: 'CP-012', tipo: 'REGRESIÓN', estado: 'FALLÓ',
            titulo: 'Se puede agregar una entrada de Work Experience',
            pre: 'En Qualifications.', datos: 'Empresa = "Empresa QA Test"; Cargo = "QA Engineer"',
            pasos: ['Click en Add de Work Experience', 'Completar empresa y cargo', 'Click en Save'],
            esperado: 'Se guarda el registro: aparece toast de éxito o la fila en la tabla.',
            obtenido: 'FALLÓ: no se confirmó el guardado en el demo (assertion); a revisar selector/estado. No bloquea el flujo.' },
          { id: 'CP-013', tipo: 'REGRESIÓN', estado: 'FALLÓ',
            titulo: 'Se puede agregar una entrada de Education',
            pre: 'En Qualifications.', datos: 'Nivel educativo (primer valor del combo)',
            pasos: ['Click en Add de Education', 'Seleccionar un nivel', 'Click en Save'],
            esperado: 'El sistema guarda sin error (la URL no contiene "error").',
            obtenido: 'FALLÓ: strict mode violation, el selector de la tarjeta Education matchea varios nodos del DOM público. Deuda de automatización (refinar selector), no defecto de producto.' },
          { id: 'CP-014', tipo: 'FUNCIONAL', estado: 'PASÓ',
            titulo: 'Guardar Work Experience vacío muestra validación',
            pre: 'En Qualifications.', datos: 'Formulario vacío',
            pasos: ['Click en Add de Work Experience', 'Click en Save sin completar'],
            esperado: 'Permanece en la página mostrando validación (no crashea).',
            obtenido: 'PASÓ (marcado "flaky": falló el primer intento por timing y pasó al reintentar).' },
          { id: 'CP-015', tipo: 'FUNCIONAL', estado: 'PASÓ',
            titulo: 'Las secciones Skills y Languages están presentes',
            pre: 'En Qualifications.', datos: 'N/A',
            pasos: ['Revisar el contenido de la página'],
            esperado: 'El contenido incluye las secciones Skills y Languages.',
            obtenido: 'PASÓ.' },
        ],
      },
    ],
    execution: { total: 15, passed: 11, failed: 3, skipped: 1 },
  },
  {
    sprint: 'Sprint N+1',
    desc: 'Backend de My Info – Qualifications y Edit Employee – Report to · Pantalla de Edit Employee – Report to.',
    modules: [
      {
        name: 'PIM – Edit Employee – Report to', range: 'CP-016 a CP-020',
        cases: [
          { id: 'CP-016', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'La pestaña Report-to carga correctamente',
            pre: 'Admin logueado; perfil de empleado abierto.', datos: 'N/A',
            pasos: ['Abrir el perfil de un empleado', 'Ir a la pestaña Report-to'],
            esperado: 'Se ve el contenido de Supervisors / Report-to.',
            obtenido: 'PASÓ.' },
          { id: 'CP-017', tipo: 'REGRESIÓN', estado: 'PASÓ',
            titulo: 'La sección Supervisors es visible y tiene botón Add',
            pre: 'En Report-to.', datos: 'N/A',
            pasos: ['Observar la sección Supervisors'],
            esperado: 'El botón Add es visible y se muestra "Assigned Supervisors".',
            obtenido: 'PASÓ.' },
          { id: 'CP-018', tipo: 'REGRESIÓN', estado: 'PASÓ',
            titulo: 'El formulario de nuevo supervisor muestra los campos necesarios',
            pre: 'En Report-to.', datos: 'N/A',
            pasos: ['Click en Add de Supervisors'],
            esperado: 'Aparece el autocomplete para buscar empleado y el combo Reporting Method.',
            obtenido: 'PASÓ.' },
          { id: 'CP-019', tipo: 'FUNCIONAL', estado: 'FALLÓ',
            titulo: 'El botón Cancel en el formulario de supervisor cierra sin guardar',
            pre: 'En Report-to.', datos: 'N/A',
            pasos: ['Contar las filas actuales', 'Click en Add de Supervisors', 'Click en Cancel'],
            esperado: 'El número de filas no aumenta (no se agrega supervisor).',
            obtenido: 'FALLÓ: la assertion sobre el conteo/cierre no se cumplió como se esperaba; a confirmar si es timing de la automatización.' },
          { id: 'CP-020', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'La sección Subordinates es visible',
            pre: 'En Report-to.', datos: 'N/A',
            pasos: ['Revisar el contenido de la página'],
            esperado: 'El contenido incluye la sección Subordinates.',
            obtenido: 'PASÓ.' },
        ],
      },
    ],
    execution: { total: 5, passed: 4, failed: 1, skipped: 0 },
  },
  {
    sprint: 'Sprint N+2',
    desc: 'Back y Front del módulo Admin – Add (asignación de perfil/usuario a empleado existente).',
    modules: [
      {
        name: 'Admin – User Management – Add User', range: 'CP-021 a CP-025',
        cases: [
          { id: 'CP-021', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'El listado de usuarios (Admin > Users) carga correctamente',
            pre: 'Admin logueado.', datos: 'N/A',
            pasos: ['Ir a Admin > User Management > Users'],
            esperado: 'Se ve el título "System Users" y la grilla con al menos una fila.',
            obtenido: 'PASÓ.' },
          { id: 'CP-022', tipo: 'REGRESIÓN', estado: 'PASÓ',
            titulo: 'El formulario de alta de usuario contiene todos los campos',
            pre: 'En Admin > Users.', datos: 'N/A',
            pasos: ['Click en Add'],
            esperado: 'Se ve el título "Add User" y los campos User Role, Employee Name, Status, Username y Password.',
            obtenido: 'PASÓ.' },
          { id: 'CP-023', tipo: 'REGRESIÓN', estado: 'PASÓ',
            titulo: 'Guardar formulario vacío muestra errores de validación',
            pre: 'En Add User.', datos: 'Formulario vacío',
            pasos: ['Click en Save sin completar'],
            esperado: 'Aparecen mensajes "Required" en los campos obligatorios.',
            obtenido: 'PASÓ.' },
          { id: 'CP-024', tipo: 'FUNCIONAL', estado: 'PASÓ',
            titulo: 'Contraseñas que no coinciden muestran error de confirmación',
            pre: 'En Add User.', datos: 'Password = "Admin@12345"; Confirm = "DiferentePass!99"',
            pasos: ['Ingresar contraseña y una confirmación distinta', 'Click en Save'],
            esperado: 'Se muestra un error de coincidencia de contraseña.',
            obtenido: 'PASÓ (ver BUG-05: la política acepta contraseñas sin carácter especial).' },
          { id: 'CP-025', tipo: 'SMOKE', estado: 'PASÓ',
            titulo: 'Se puede filtrar el listado de usuarios por rol',
            pre: 'En Admin > Users.', datos: 'User Role = "Admin"',
            pasos: ['Seleccionar User Role = Admin', 'Click en Search'],
            esperado: 'La grilla queda visible con filas coincidentes o "No Records Found".',
            obtenido: 'PASÓ.' },
        ],
      },
    ],
    execution: { total: 5, passed: 5, failed: 0, skipped: 0 },
  },
];

// ── Casos de prueba de la API del Clima detallados (Actividad 3) ──────────────
// Cada caso: { id, request, pre, pasos[], esperado, obtenido }
const API_GROUPS = [
  {
    group: 'Realtime Weather API — GET /current.json', range: 'CP-API-001 a CP-API-005',
    cases: [
      { id: 'CP-API-001 [SMOKE][HAPPY] Ciudad válida', request: 'GET /current.json?q={{city_valid}}&key={{api_key}}&aqi=yes',
        pre: 'API key válida cargada.', pasos: ['Enviar GET con ciudad válida'],
        esperado: 'Status 200; responseTime < 3000 ms; existe location (name, country, lat, lon, localtime) y current (temp_c, temp_f, humidity, wind_kph, feelslike_c, condition.text/icon); Content-Type application/json.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-002 [HAPPY] Coordenadas GPS', request: 'GET /current.json?q=-34.6037,-58.3816&key={{api_key}}',
        pre: 'API key válida.', pasos: ['Enviar GET con coordenadas'],
        esperado: 'Status 200; location.lat y lon coherentes con lo enviado; current.last_updated con formato fecha.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-003 [UNHAPPY] Sin API key', request: 'GET /current.json?q={{city_valid}} (sin key)',
        pre: 'N/A.', pasos: ['Enviar GET omitiendo la key'],
        esperado: 'Status 401; body.error con code (number) y message (string) no vacío.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-004 [UNHAPPY] API key inválida', request: 'GET /current.json?key=INVALID_KEY_123ABC&q={{city_valid}}',
        pre: 'N/A.', pasos: ['Enviar GET con key inválida'],
        esperado: 'Status 401; error.code en [2006, 2007, 2008].',
        obtenido: 'PASÓ (se ajustó: el proveedor cambió de 403 a 401).' },
      { id: 'CP-API-005 [UNHAPPY] Ciudad inexistente', request: 'GET /current.json?q={{city_invalid}}&key={{api_key}}',
        pre: 'API key válida.', pasos: ['Enviar GET con ciudad inexistente'],
        esperado: 'Status 400; error.code = 1006 (no matching location).',
        obtenido: 'PASÓ.' },
    ],
  },
  {
    group: 'Forecast Weather API — GET /forecast.json', range: 'CP-API-006 a CP-API-010',
    cases: [
      { id: 'CP-API-006 [SMOKE][HAPPY] Pronóstico 3 días', request: 'GET /forecast.json?q={{city_valid}}&days=3&key={{api_key}}',
        pre: 'API key válida.', pasos: ['Enviar GET con days=3'],
        esperado: 'Status 200; body con keys location, current y forecast; forecastday con 3 entradas; cada día con date, day y hour (24); day con maxtemp_c, mintemp_c y condition.text.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-007 [HAPPY] Pronóstico 1 día', request: 'GET /forecast.json?q={{city_valid}}&days=1',
        pre: 'API key válida.', pasos: ['Enviar GET con days=1'],
        esperado: 'Status 200; forecastday con exactamente 1 entrada; la fecha es hoy o futura.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-008 [DEFAULT] Sin parámetro days', request: 'GET /forecast.json?q={{city_valid}} (sin days)',
        pre: 'API key válida.', pasos: ['Enviar GET sin el parámetro days'],
        esperado: 'Status 200; sigue habiendo forecast.forecastday (array no vacío) usando el valor por defecto.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-009 [UNHAPPY] Ciudad inválida', request: 'GET /forecast.json?q={{city_invalid}}&days=3',
        pre: 'API key válida.', pasos: ['Enviar GET con ciudad inválida'],
        esperado: 'Status 400; error.code = 1006.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-010 [UNHAPPY] Sin API key', request: 'GET /forecast.json?q={{city_valid}}&days=3 (sin key)',
        pre: 'N/A.', pasos: ['Enviar GET sin la key'],
        esperado: 'Status 401; body.error presente.',
        obtenido: 'PASÓ.' },
    ],
  },
  {
    group: 'History Weather API — GET /history.json', range: 'CP-API-011 a CP-API-015',
    cases: [
      { id: 'CP-API-011 [SMOKE][HAPPY] Fecha histórica válida', request: 'GET /history.json?q={{city_valid}}&dt={{date_past}}&key={{api_key}}',
        pre: 'dt es una fecha pasada válida.', pasos: ['Enviar GET con dt en el pasado'],
        esperado: 'Status 200; forecast.forecastday[0] con la fecha solicitada y hour con datos hora a hora.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-012 [HAPPY] Rango de fechas', request: 'GET /history.json?q={{city_valid}}&dt=...&end_dt=...',
        pre: 'Rango pasado válido.', pasos: ['Enviar GET con dt y end_dt'],
        esperado: 'Status 200; forecastday con múltiples días dentro del rango.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-013 [UNHAPPY] Fecha futura', request: 'GET /history.json?q={{city_valid}}&dt={{date_future}}',
        pre: 'API key válida.', pasos: ['Enviar GET con dt futura'],
        esperado: 'Status 400; body.error presente (fecha fuera del rango permitido).',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-014 [UNHAPPY] Sin parámetro dt', request: 'GET /history.json?q={{city_valid}} (sin dt)',
        pre: 'API key válida.', pasos: ['Enviar GET sin dt'],
        esperado: 'Status 400; body.error presente (parámetro obligatorio faltante).',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-015 [UNHAPPY] Sin API key', request: 'GET /history.json?q={{city_valid}}&dt={{date_past}} (sin key)',
        pre: 'N/A.', pasos: ['Enviar GET sin la key'],
        esperado: 'Status 401; body.error presente.',
        obtenido: 'PASÓ.' },
    ],
  },
  {
    group: 'Alerts Weather API — GET /alerts.json', range: 'CP-API-016 a CP-API-020',
    cases: [
      { id: 'CP-API-016 [SMOKE][HAPPY] Solicitud válida', request: 'GET /alerts.json?q={{city_valid}}&key={{api_key}}&alerts=yes',
        pre: 'API key válida.', pasos: ['Enviar GET con ciudad válida'],
        esperado: 'Status 200; existe la estructura alerts (objeto con array alert, eventualmente vacío).',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-017 [HAPPY] Ciudad con posibles alertas', request: 'GET /alerts.json?q=<ciudad EE.UU.>&key={{api_key}}',
        pre: 'API key válida.', pasos: ['Enviar GET con ciudad de EE.UU.'],
        esperado: 'Status 200; estructura de alerts válida (si hay alertas activas, cada alert con sus campos).',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-018 [UNHAPPY] Ciudad inválida', request: 'GET /alerts.json?q={{city_invalid}}&key={{api_key}}',
        pre: 'API key válida.', pasos: ['Enviar GET con ciudad inválida'],
        esperado: 'Status 400; error.code = 1006.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-019 [UNHAPPY] Sin API key', request: 'GET /alerts.json?q={{city_valid}} (sin key)',
        pre: 'N/A.', pasos: ['Enviar GET sin la key'],
        esperado: 'Status 401; body.error presente.',
        obtenido: 'PASÓ.' },
      { id: 'CP-API-020 [UNHAPPY] Sin parámetro q', request: 'GET /alerts.json?key={{api_key}} (sin q)',
        pre: 'API key válida.', pasos: ['Enviar GET sin q'],
        esperado: 'Status 400; body.error presente (parámetro obligatorio q faltante).',
        obtenido: 'PASÓ.' },
    ],
  },
];

// ── Bugs detallados (Bug Tracker) ─────────────────────────────────────────────
const BUGS = [
  { id: 'BUG-01', sprint: 'Sprint N', module: 'PIM - Employee List', severity: 'LOW', priority: 'MEDIUM', status: 'OPEN',
    title: 'El botón Reset no limpia todos los filtros de búsqueda',
    steps: ['Ir a PIM > Employee List', 'Seleccionar un Employment Status del dropdown', 'Ingresar texto en Employee Name', 'Click en Reset'],
    expected: 'Todos los campos del formulario quedan en su estado inicial.',
    actual: 'Solo se limpia Employee Name; los demás filtros retienen el valor.',
    reportedBy: 'Tester 1' },
  { id: 'BUG-02', sprint: 'Sprint N', module: 'PIM - Add Employee', severity: 'HIGH', priority: 'HIGH', status: 'OPEN',
    title: 'Se permite crear empleados con Employee ID duplicado',
    steps: ['Ir a PIM > Add Employee', 'Ingresar un Employee ID ya existente (ej. 0001)', 'Completar First Name y Last Name', 'Click en Save'],
    expected: 'El sistema rechaza el ID duplicado y muestra error de validación.',
    actual: 'El empleado se crea con el mismo ID, generando duplicidad (afecta integridad referencial).',
    reportedBy: 'Tester 1' },
  { id: 'BUG-03', sprint: 'Sprint N', module: 'PIM - My Info - Qualifications', severity: 'MEDIUM', priority: 'MEDIUM', status: 'IN_PROGRESS',
    title: 'Acepta fecha de fin anterior a la fecha de inicio en Work Experience',
    steps: ['Ir a My Info > Qualifications', 'Add en Work Experience', 'From = 2023-06-01 y To = 2022-01-01', 'Click en Save'],
    expected: 'El sistema rechaza el rango y muestra "To date must be after From date".',
    actual: 'El registro se guarda sin validar el rango de fechas.',
    reportedBy: 'Tester 2' },
  { id: 'BUG-04', sprint: 'Sprint N+1', module: 'PIM - Edit Employee - Report to', severity: 'HIGH', priority: 'HIGH', status: 'OPEN',
    title: 'El autocomplete de supervisor tarda más de 10s con base de datos grande',
    steps: ['Tener más de 200 empleados cargados', 'Ir a PIM > Employee > Report-to', 'Add en Supervisors', 'Empezar a escribir un nombre'],
    expected: 'Las sugerencias aparecen en menos de 2 segundos.',
    actual: 'Las sugerencias tardan 10-15 segundos, bloqueando la UI (degrada la usabilidad en producción).',
    reportedBy: 'Tester 3 (Performance)' },
  { id: 'BUG-05', sprint: 'Sprint N+2', module: 'Admin - User Management', severity: 'MEDIUM', priority: 'HIGH', status: 'OPEN',
    title: 'La política acepta contraseñas sin caracteres especiales',
    steps: ['Ir a Admin > User Management > Users', 'Click en Add', 'Completar todos los campos', 'Contraseña "Password1" y confirmar', 'Click en Save'],
    expected: 'El sistema exige al menos 1 carácter especial y rechaza la contraseña.',
    actual: 'El usuario se crea con esa contraseña débil sin error.',
    reportedBy: 'Tester 1' },
  { id: 'BUG-06', sprint: 'Sprint N+3', module: 'Dashboard - Widget Clima', severity: 'HIGH', priority: 'HIGH', status: 'OPEN',
    title: 'No muestra mensaje de error cuando la API del clima no responde',
    steps: ['Configurar una API key inválida en el backend del widget', 'Cargar el dashboard principal', 'Observar el widget de clima'],
    expected: 'Tras un timeout (ej. 5s) el widget muestra "No se pudo cargar el clima" e ícono de error.',
    actual: 'El widget queda en spinner de carga indefinido, sin feedback al usuario.',
    reportedBy: 'Tester 2' },
];

// ── Calendario por sprint (incluye hitos de performance) ──────────────────────
const SPRINT_CALENDAR = [
  ['Sprint N', 'Días 1-3: diseño de casos (Employee List, Add Employee, Qualifications).\nDías 4-7: ejecución funcional + automatización E2E + smoke de performance en cada despliegue.\nDías 8-9: regresión y prueba de carga (Load) del incremento al cierre.\nDía 10: reporte de resultados y bugs.'],
  ['Sprint N+1', 'Días 1-2: diseño de casos Edit Employee – Report to + regresión de Qualifications.\nDías 3-6: ejecución + automatización + smoke de performance por despliegue.\nDías 7-8: regresión + Load test al cierre (foco en el autocomplete de supervisor).\nDías 9-10: reporte.'],
  ['Sprint N+2', 'Días 1-2: diseño de casos Admin – Add User.\nDías 3-6: ejecución + automatización + seguridad básica (política de contraseña) + smoke de performance.\nDías 7-9: regresión + Load test al cierre.\nDía 10: reporte.'],
  ['Sprint N+3', 'Días 1-2: diseño de casos de API del Clima y del widget.\nDías 3-6: ejecución Postman/Newman + E2E del widget + smoke de performance.\nDías 7-9: regresión integral + Load test global; Stress antes del paso a producción.\nDía 10: reporte final consolidado.'],
];

// ── Matriz de frecuencia de performance (Pregunta 5) ──────────────────────────
const PERF_MATRIX = [
  ['Smoke de performance', 'Cada despliegue en Staging', 'Control más barato y temprano: detecta degradaciones de tiempos de respuesta apenas aparecen.'],
  ['Pruebas de carga (Load)', 'Al cierre de cada sprint', 'Mide el incremento nuevo y estable bajo la demanda concurrente proyectada.'],
  ['Pruebas de estrés (Stress)', 'Antes de releases o pasos a producción', 'Busca el punto de quiebre y valida auto-escalado y recuperación cuando el riesgo es mayor.'],
  ['Estabilidad (Endurance)', 'Mensual / ciclos de estabilización', 'Detecta memory leaks y agotamiento de conexiones que solo aparecen con el tiempo.'],
  ['Volumen (Volume)', 'Ante crecimiento del histórico', 'Verifica índices y tiempos de las grillas de PIM cuando crece la base de datos.'],
];

// ── Resumen consolidado de ejecución (Sprint N a N+3) ─────────────────────────
const EXEC_SUMMARY = [
  ['Frontend núcleo (Actividad 2, CP-001 a CP-025)', '25', '20', '4', '1', '80%'],
  ['Frontend regresión adicional (CP-026 a CP-125)', '100', '55', '45', '0', '55%'],
  ['API del Clima (Actividad 3, Newman)', '20', '20', '0', '0', '100%'],
  ['Total acumulado', '145', '95', '49', '1', '65.5%'],
];

// ── Devolución del docente atendida ───────────────────────────────────────────
const DEVOLUCION = [
  ['Sin referencia concreta a cada pregunta; títulos cambiados', 'Cada sección lleva el número de pregunta y transcribe el enunciado; se agregó una guía de lectura inicial.'],
  ['7a: se omite performance en el calendario', 'Se agregaron hitos de performance (smoke por despliegue, Load al cierre, Stress antes de producción) en el calendario por sprint.'],
  ['7a: contradicción entre criterio de salida y waiver', 'Se aclaró que el waiver solo aplica a falsos positivos del entorno, nunca a HIGH/CRITICAL reales de producto.'],
  ['7b: cobertura pobre, solo checklist', 'Los 25 casos ahora son fichas detalladas (tipo, precondiciones, datos, pasos, esperado y obtenido).'],
  ['7c: no hay escritura de casos de API', 'Los 20 casos de API ahora son fichas detalladas (endpoint, request, pasos, status y aserciones esperadas).'],
  ['Reporte de ejecución: solo pass/fail, no por caso', 'Cada caso muestra resultado obtenido/estado; se referencian las evidencias en Allure, Playwright HTML y el Excel por caso.'],
  ['Reporte de bugs: no permiten reproducir', 'Cada bug incluye pasos de reproducción, esperado y obtenido; el tablero de Trello se publica con enlace sin vencimiento.'],
];

// ── Mind Map funcional de OrangeHRM (Actividad 1 → entregable 7.e) ────────────
// Cada nodo: { lvl (0..3), t (texto), tag ('Principal'|'Secundaria'|'Crítica'|'Nuevo'|'Futuro'|'') }
const MINDMAP = [
  { lvl: 0, t: 'OrangeHRM — Sistema de Gestión de Personas', tag: '' },
  { lvl: 1, t: 'Acceso y Dashboard', tag: 'Principal' },
  { lvl: 2, t: 'Login / Logout y recuperación de contraseña', tag: '' },
  { lvl: 2, t: 'Dashboard: widgets, accesos rápidos (Quick Launch)', tag: '' },
  { lvl: 2, t: 'Widget de Clima (integración con WeatherAPI.com)', tag: 'Nuevo' },
  { lvl: 1, t: 'PIM — Personnel Information Management', tag: 'Principal' },
  { lvl: 2, t: 'Employee List: búsqueda, filtros y grilla principal', tag: '' },
  { lvl: 2, t: 'Add Employee: alta de legajo, Employee ID, login opcional', tag: '' },
  { lvl: 2, t: 'Edit Employee: Personal / Contact / Job Details', tag: '' },
  { lvl: 2, t: 'Edit Employee: Report-to (supervisores y subordinados)', tag: '' },
  { lvl: 2, t: 'Configuración PIM: Optional Fields, Custom Fields, Reporting Methods', tag: 'Secundaria' },
  { lvl: 1, t: 'My Info (Employee Self-Service)', tag: 'Principal' },
  { lvl: 2, t: 'Qualifications: Work Experience, Education, Skills, Languages', tag: '' },
  { lvl: 2, t: 'Personal / Contact / Emergency Contacts / Dependents', tag: 'Secundaria' },
  { lvl: 1, t: 'Admin', tag: 'Principal' },
  { lvl: 2, t: 'User Management: Add User y asignación de perfil/rol', tag: '' },
  { lvl: 2, t: 'Job, Organization, Qualifications, Nationalities (parametrización)', tag: 'Secundaria' },
  { lvl: 1, t: 'Time — Attendance (Punch In/Out)', tag: 'Crítica' },
  { lvl: 2, t: 'Registro de ingreso/egreso (riesgo de concurrencia en picos)', tag: '' },
  { lvl: 2, t: 'Timesheets y reportes de asistencia', tag: 'Secundaria' },
  { lvl: 1, t: 'Otros módulos del ecosistema', tag: 'Secundaria' },
  { lvl: 2, t: 'Leave, Performance, Directory, Maintenance, Buzz, Claim', tag: '' },
  { lvl: 1, t: 'Recruitment (Atracción y Selección)', tag: 'Futuro' },
  { lvl: 2, t: 'Vacantes, postulantes, carga de CV, flujo de contratación', tag: '' },
];

// ── Mapa de entregables y artefactos vivos (modelo de entrega por enlaces) ────
const ENTREGABLES = [
  ['7.a Plan de pruebas general', 'Sección 7a de este documento (propósito, estrategia, calendario con performance, criterios de entrada/salida, gestión de defectos).'],
  ['7.b Casuística de frontend (Sprint N, N+1, N+2)', 'Sección 7b (25 casos detallados) + planilla Casos_de_Prueba_OrangeHRM.xlsx (formato MOLDE) + reporte Allure por caso.'],
  ['7.c API del Clima + colección Postman', 'Sección 7c (20 casos detallados) + colección api-tests/collections/WeatherAPI.postman_collection.json y su entorno.'],
  ['7.d Reporte de pruebas y bugs', 'Sección 7d + Bug Tracker (http://localhost:3000) + Tablero Trello (enlace público sin vencimiento) + reportes Newman/Allure.'],
  ['7.e Mind Map de OrangeHRM', 'Sección 7e de este documento (mapa funcional del sitio: funcionalidades principales y secundarias).'],
];

const SEV_LABEL = { CRITICAL: 'CRITICAL', HIGH: 'HIGH', MEDIUM: 'MEDIUM', LOW: 'LOW' };
const STATUS_LABEL = { OPEN: 'Abierto', IN_PROGRESS: 'En progreso', RESOLVED: 'Resuelto', CLOSED: 'Cerrado' };

module.exports = {
  AUTHORS, ENUNCIADOS, FRONTEND_SPRINTS, API_GROUPS, BUGS,
  SPRINT_CALENDAR, PERF_MATRIX, EXEC_SUMMARY, DEVOLUCION,
  MINDMAP, ENTREGABLES,
  SEV_LABEL, STATUS_LABEL,
};
