server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Dashboard principal
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Reporte HTML de Playwright
    location /playwright-report/ {
        alias /usr/share/nginx/html/playwright-report/;
        try_files $uri $uri/ =404;
        autoindex on;
    }

    # Reporte HTML de Newman (API Weather)
    location /api-report/ {
        alias /usr/share/nginx/html/api-report/;
        try_files $uri $uri/ =404;
        autoindex on;
    }

    # Cabeceras de cache para archivos estáticos
    location ~* \.(css|js|png|jpg|ico|svg)$ {
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }
}
